steps:
  # 1. Build the Docker image from the project subfolder
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Image
    args:
      - build
      - -t
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest
      - services_copy-of-copy-of-atip-textile-jack_1773011278.313000 (1)

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest

  # 3. Deploy to Cloud Run in US-WEST1
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy US
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:latest
      - --region=$_DEPLOY_REGION
      - --platform=$_PLATFORM
      - --allow-unauthenticated

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
